spring.application.name=consultation-service
server.port=8085

# H2 Database
spring.datasource.url=jdbc:h2:mem:consultationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 Console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console